[tool.ariadne-codegen]
remote_schema_url = "http://localhost:8000/graphql"
remote_schema_path = "remote_client/schema.graphql"
queries_path = "remote_client/queries.graphql"
target_package_path = "pixie_sdk/remote_client/generated"
target_package_name = "generated"
client_name = "RemoteClient"
include_all_inputs = true
include_all_enums = true
